# Generated by Django 4.2.21 on 2025-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('numero_sequenziale', models.AutoField(primary_key=True, serialize=False)),
                ('codice_articolo', models.CharField(max_length=100)),
                ('trasposizione', models.CharField(max_length=100)),
                ('descrizione', models.CharField(max_length=250)),
                ('um', models.CharField(max_length=10)),
                ('pezzatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('giacenza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codice_fornitore', models.CharField(max_length=100)),
                ('anagrafica_fornitore', models.CharField(max_length=250)),
                ('scheda_riferimento', models.CharField(max_length=10)),
                ('conta_arrivi', models.IntegerField()),
                ('data_conferimento', models.DateField(auto_now_add=True)),
                ('partita_produzione', models.CharField(max_length=250)),
                ('quantita_conferita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='articolo',
            constraint=models.UniqueConstraint(fields=('numero_sequenziale',), name='unique_numero_sequenziale'),
        ),
    ]
