# Generated by Django 5.0.14 on 2025-05-19 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_deposito', models.CharField(max_length=100, unique=True)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Deposito',
                'verbose_name_plural': 'Depositi',
                'ordering': ['nome_deposito'],
            },
        ),
        migrations.CreateModel(
            name='Posizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_posizione', models.CharField(help_text='Es. Scaffale A, Ripiano 3, Settore Nord', max_length=100)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posizioni_deposito', to='inventory.deposito')),
            ],
            options={
                'verbose_name': 'Posizione',
                'verbose_name_plural': 'Posizioni',
                'ordering': ['deposito__nome_deposito', 'nome_posizione'],
                'unique_together': {('deposito', 'nome_posizione')},
            },
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequenziale', models.CharField(help_text="Codice univoco dell'articolo (es. SKU, Part Number)", max_length=50, unique=True)),
                ('nome_articolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('tipologia_articolo', models.CharField(choices=[('MAT_PRIMA', 'Materia Prima'), ('SEMILAVORATO', 'Semilavorato'), ('PROD_FINITO', 'Prodotto Finito'), ('CONSUMABILE', 'Materiale di Consumo'), ('RICAMBIO', 'Ricambio'), ('ATTREZZATURA', 'Attrezzatura'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20)),
                ('unita_di_misura', models.CharField(choices=[('PZ', 'Pezzi'), ('KG', 'Chilogrammi'), ('LT', 'Litri'), ('MT', 'Metri'), ('MQ', 'Metri Quadri'), ('MC', 'Metri Cubi'), ('PALLET', 'Pallet'), ('SCATOLA', 'Scatola'), ('ALTRO', 'Altro')], default='PZ', max_length=10)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantita', models.IntegerField(default=0, help_text='Quantità totale disponibile')),
                ('data_inserimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Conferimento/Inserimento')),
                ('data_ultima_modifica', models.DateTimeField(auto_now=True)),
                ('attivo', models.BooleanField(default=True)),
                ('codice_fornitore', models.CharField(blank=True, max_length=50, null=True)),
                ('partita_produzione', models.CharField(blank=True, max_length=50, null=True)),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articoli', to='inventory.deposito')),
                ('posizione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articoli', to='inventory.posizione')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['nome_articolo'],
            },
        ),
    ]
