# Generated by Django 4.2.21 on 2025-05-13 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articolo',
            name='unique_numero_sequenziale',
        ),
        migrations.AlterField(
            model_name='articolo',
            name='conta_arrivi',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='data_conferimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='partita_produzione',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='trasposizione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
